# Generated by Django 3.2.7 on 2021-10-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_posted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_on',
            new_name='datetime',
        ),
    ]
