# Generated by Django 3.2.7 on 2021-10-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_posted_on_comment_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='date',
        ),
    ]
